Repository TheSpecsss/neu-wallet-frontend, pull requests merged in 2025-02, with the labels that each got.

#22 Implemented the landingpage ui
  assets/NEUBackground.png
  assets/NEUlogo.png
  bun.lock
  package.json
  screens/LandingScreen.tsx
Labels: enhancement, good first issue

#50 Need a review for setting up the baseAPI for backend
  .env.example
  App.tsx
  api/axiosInstance.ts
  api/userApi.ts
  bun.lock
  hooks/UserList.tsx
  package.json
Labels: help wanted

#66 [feat] TS-42: register screen integration
  .env
  .env.example
  .gitignore
  App.tsx
  api/axiosInstance.ts
  api/createUser.ts
  api/userApi.ts
  bun.lockb
  screens/RegisterScreen.tsx
Labels: enhancement
